# -*- coding: utf-8 -*-
"""CIS 586 - Predicative Maintenance Using Vehicle Engine Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQ6dgGFpvPZeciL9o7pr1XgFJKBKdcYT
"""

from google.colab import drive
# Mount Google Drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, confusion_matrix, roc_curve, roc_auc_score, classification_report
from sklearn.tree import plot_tree

"""## **Data Exploration**"""

# Path to your CSV file in Google Drive
file_path = '/content/drive/MyDrive/Grad School/CIS 586/Project/Data/engine_data.csv'

# Read the CSV file
engine = pd.read_csv(file_path)
engine.head()

# Expoloratory Data Analysis
engine.info()

engine.isnull().sum()
# no null values present in the data

engine.dtypes

# all the data types are numeric

engine.describe()

engine['Engine Condition'].value_counts()

"""# Initial Data Ananlysis"""

sns.countplot(x=engine['Engine Condition'])
plt.show()

sns.countplot(engine)

sns.displot(data=engine['Engine rpm'], bins= 20, kde= True)
plt.show()

sns.displot(data=engine['Fuel pressure'], bins= 20, kde= True)
plt.show()

sns.displot(data=engine['lub oil temp'], bins= 20, kde= True)
plt.show()

#visualizing the data
sns.pairplot(engine)
plt.show()

# Checking the correlation between parameters
sns.heatmap(engine.corr(), annot=True, cmap='crest')

# based on the results, I may want to try to create some interaction variables to find some stronger correlations, but I'm not sure which variables.

"""## **Data Preprocessing**"""

# Data Preprocessing, normalzing data using Scaler
scaler = MinMaxScaler()

X = engine.drop('Engine Condition', axis=1)
y = engine['Engine Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

# Preprocess the data by scaling using MinMaxScaler and StandardScaler
X_train_minmax = scaler.fit_transform(X_train)
X_test_minmax = scaler.transform(X_test)

X_train_minmax

# Initialize and train a Random Forest classifier for feature selection (FS)
rf_FS = RandomForestClassifier(random_state=45)
rf_FS.fit(X_train_minmax, y_train)

rf_FS.score(X_test_minmax, y_test)

# Parameters for the grid search to test
grid_param = {
    'n_estimators': [100, 120],
    'criterion': ['gini', 'entropy'],
    'max_depth': range(2, 35, 10),
    'max_features': ['auto', 'log2'],
    'min_samples_leaf': range(10, 50, 10),
    'min_samples_split': range(10, 20, 5)
}

cv = StratifiedKFold(n_splits=5)

# Running the GridSearchCV using stratified Kfolds to assess best tuning of the parameters
grid_search = GridSearchCV(estimator=rf_FS, param_grid=grid_param, cv=cv, n_jobs= -1, verbose= 3)
grid_search.fit(X_train_minmax, y_train)
#took 44 mins to run, may need to reduce some ranges.

# Assessing the best parameters for th random forest tree to better identify the best features in the given dataset
grid_search.best_params_

"""## **Feature Selection**"""

# Updating the parameters to optimize the random forest feature selector to identify best parameters
opt_rf_fs = RandomForestClassifier( n_estimators= 120,
                                    criterion='gini',
                                    max_depth= 22,
                                    max_features= 'auto',
                                    min_samples_leaf= 40,
                                    min_samples_split= 10,
                                    random_state= 23
)
opt_rf_fs.fit(X_train_minmax, y_train)

# opt_rf_fs.score(X_test_minmax, y_test)
# #accuracy improved 2%!

# Assessing most important features based on optimized RF
feature_importances = opt_rf_fs.feature_importances_

# Create a DataFrame to display feature importances
feature_importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Display the top features
print(feature_importance_df.head(10))

# using the top two since the importance isn't that strong

"""## **Random Forest Classification Analysis**"""

# filtering the engine dataset to only the top 3 features
engine_opt = engine.iloc[:, [0, 2, 4, 6]]

# Refitting the Random Forest Model to see if there was any improvement with th e new features only
scaler = MinMaxScaler()

X_opt = engine_opt.drop('Engine Condition', axis=1)
y_opt = engine_opt['Engine Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_opt, y_opt, test_size=0.2, random_state=32)

# Preprocess the data by scaling using MinMaxScaler
X_train_minmax = scaler.fit_transform(X_train)
X_test_minmax = scaler.transform(X_test)

# Initialize and re-train the Random Forest classifier with updated features selected
rf_clf = RandomForestClassifier(random_state=32)
rf_clf.fit(X_train_minmax, y_train)

rf_clf= RandomForestClassifier( n_estimators= 120,
                                criterion='gini',
                                max_depth= 22,
                                max_features= 'auto',
                                min_samples_leaf= 40,
                                min_samples_split= 10,
                                random_state= 35
)
rf_clf.fit(X_train_minmax, y_train)

# Checking for accuracy before one more grid search to compare accuracy for best results.
rf_clf.score(X_test_minmax, y_test)

# Reassessing parameters given reduced dataset
grid_param2 = {
    'n_estimators': [100, 120],
    'criterion': ['gini', 'entropy'],
    'max_depth': range(5, 25, 5),
    'max_features': ['auto', 'log2'],
    'min_samples_leaf': range(30, 120, 30),
    'min_samples_split': range(10, 20, 5)
}

# Second GridSearch on optimized dataset to get refined parameters to produce best possible accuracy
cv = StratifiedKFold(n_splits=5)
grid_search = GridSearchCV(estimator=rf_clf, param_grid=grid_param2, cv= cv, scoring='accuracy', n_jobs= -1, verbose= 3)
grid_search.fit(X_train_minmax, y_train)
#26 minutes to run

# Assessing the best parameters for th random forest tree to better identify the best features in the given dataset
grid_search.best_params_

# Updating the parameters to optimize the random forest feature selector to identify best parameters
opt_rf_clf= RandomForestClassifier( n_estimators= 120,
                                    criterion='entropy',
                                    max_depth= 15,
                                    max_features= 'auto',
                                    min_samples_leaf= 90,
                                    min_samples_split= 10,
                                    random_state= 25
)
opt_rf_clf.fit(X_train_minmax, y_train)

# Get the class names as a list of strings
class_names = [str(cls) for cls in opt_rf_clf.classes_]

# Choose one tree from the random forest to visualize
tree = opt_rf_clf.estimators_[1]

# Plot the single decision tree
plt.figure(figsize=(12, 8))
plot_tree(tree, feature_names=X_opt.columns, class_names=class_names, filled=True)
plt.show()

opt_rf_clf.score(X_test_minmax, y_test)
# the accuracy slightly increased, thus, I feel comfortable leaving as is or keeping the new parameters.

# Making a predictions on the test set
y_pred = opt_rf_clf.predict(X_test_minmax)
print('Random Forest Classifier Accuracy: ',accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

# confusion matrix for random forest classifier
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted Outcome')
plt.ylabel('Actual Outcome')
plt.title('Confusion Matrix for Random Forest')
plt.show()

"""## **Gradient Boost Analysis**"""

# filtering the engine dataset to only the top 3 features
engine_gb = engine.iloc[:, [0, 2, 4, 6]]
# Refitting the Random Forest Model to see if there was any improvement with th e new features only
scaler = MinMaxScaler()

X_gb = engine_gb.drop('Engine Condition', axis=1)
y_gb = engine_gb['Engine Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_gb, y_gb, test_size=0.2, stratify=y_gb, random_state=15)

# Preprocess the data by scaling using MinMaxScaler
X_train_minmax = scaler.fit_transform(X_train)
X_test_minmax = scaler.transform(X_test)

# Initializing the Gradient boost
gb_clf = GradientBoostingClassifier()
gb_clf.fit(X_train_minmax, y_train)

# Checking initial accuracy
gb_clf.score(X_test_minmax, y_test)
# Slight decrease from the random forest classifier.

gb_grid_param = {
    'n_estimators': [80, 100, 120],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': range(3, 10, 2)
}

cv = StratifiedKFold(n_splits=7)
gb_grid_search = GridSearchCV(gb_clf, param_grid=gb_grid_param, cv=cv, scoring='accuracy', n_jobs= -1, verbose= 3)

#score check, about the same, slightly lower than rf.
gb_grid_search.fit(X_test_minmax, y_test)
# see best hyperparsmetrs
gb_grid_search.best_params_

# check for accuracy improvement
opt1_gb_clf= GradientBoostingClassifier( n_estimators= 100,
                                    learning_rate= 0.05,
                                    max_depth= 3
)
opt1_gb_clf.fit(X_train_minmax, y_train)

# Making a predictions on the test set
y_pred = opt1_gb_clf.predict(X_test_minmax)
print('Gradient Boost Classifier Accuracy: ',accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

# Checking to see if I can improve the accuracy above 67% by reassessing the parameters a bit more.
gb_grid_param2 = {
    'n_estimators': [100, 105, 110],
    'learning_rate': [0.02, 0.03, 0.05],
    'max_depth': [2, 3, 4]
}

cv = StratifiedKFold(n_splits=10)
gb_grid_search = GridSearchCV(gb_clf, param_grid=gb_grid_param2, cv=cv, scoring='accuracy', n_jobs= -1, verbose= 3)

gb_grid_search.fit(X_train_minmax, y_train)
# see best hyperparsmetrs
print(gb_grid_search.best_params_)

# check for accuracy improvement
opt2_gb_clf= GradientBoostingClassifier( n_estimators= 110,
                                    learning_rate= 0.05,
                                    max_depth= 2
)
opt2_gb_clf.fit(X_train_minmax, y_train)

# Making a predictions on the test set
y_pred = opt2_gb_clf.predict(X_test_minmax)
print('Gradient Boost Classifier Accuracy: ',accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

# no change in the overall accuracy, but still getting 67% as the highest which is a 1% increase from the previous geneeral hyperparameters.
# data is skewed, there is more 1's than 0's.

# confusion matrix for gradient boost classifier
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Greens')
plt.xlabel('Predicted Outcome')
plt.ylabel('Actual Outcome')
plt.title('Confusion Matrix for Gradient Boost')
plt.show()

"""## **Support Vector Machine (SVM) Analysis**"""

# filtering the engine dataset to only the top 3 features
engine_sv = engine.iloc[:, [0, 2, 4, 6]]
# Refitting the Random Forest Model to see if there was any improvement with th e new features only
scaler = MinMaxScaler()

X_sv = engine_sv.drop('Engine Condition', axis=1)
y_sv = engine_sv['Engine Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_sv, y_sv, test_size=0.2,stratify=y_sv, random_state=1)

# Preprocess the data by scaling using MinMaxScaler
X_train_minmax = scaler.fit_transform(X_train)
X_test_minmax = scaler.transform(X_test)

# Initializing the support vector machine classifier
svm_clf = SVC()
svm_clf.fit(X_train_minmax, y_train)

# Running SVM on generalized parameters
sv_clf= SVC(C= 0.1,
            kernel= 'poly',
            gamma= 'auto'
)
sv_clf.fit(X_train_minmax, y_train)

# accuracy check, initial
sv_clf.score(X_test_minmax, y_test)

svm_grid_param= {
    'C': [0.01, 0.05, 0.1, np.inf],
    'kernel': ['rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Using GridSearchCv to tune the hyperparamertes.
cv = StratifiedKFold(n_splits=5)
grid_search= GridSearchCV(svm_clf, param_grid= svm_grid_param, cv=cv, scoring= 'accuracy',  n_jobs= -1, verbose= 3)

grid_search.fit(X_train_minmax, y_train)

grid_search.best_params_

# Generating an optimized model, given GridSearchCV outputs
opt_svm_clf= SVC(C= 0.1,
                 kernel= 'rbf',
                 gamma= 'scale'
)
opt_svm_clf.fit(X_train_minmax, y_train)

# Prediciting a y to test accuracy for comparison
y_pred= opt_svm_clf.predict(X_test_minmax)

# accuracy and classification report
print('Support Vector Machine Classifier Accuracy: ',accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# the accuracy increasedby 2%, however, it did not reach the highest accuracy achieved of 67%.

# confusion matrix for Support Vector classifier
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='BuPu')
plt.xlabel('Predicted Outcome')
plt.ylabel('Actual Outcome')
plt.title('Confusion Matrix for Support Vector Machine')
plt.show()